
// ============================================
// COLOR LIBRARY ENGINE v2.0
// ============================================

document.addEventListener('DOMContentLoaded', () => {
    // Elements
    const colorInput = document.getElementById('main-color-input');
    const pipetteBtn = document.getElementById('pipette-btn');
    const previewBox = document.getElementById('preview-box');

    // Displays
    const hexDisplay = document.getElementById('hex-display');
    const rgbDisplay = document.getElementById('rgb-display');
    const hslDisplay = document.getElementById('hsl-display');
    const cmykDisplay = document.getElementById('cmyk-display');

    // Copy
    const copyCodeInput = document.getElementById('copy-code-input');
    const copyMainBtn = document.getElementById('copy-main-btn');
    const copyFeedbackBar = document.getElementById('copy-feedback-bar');

    // Export Buttons
    const exportTailwind = document.getElementById('export-tailwind');
    const exportSass = document.getElementById('export-sass');
    const exportCss = document.getElementById('export-css');

    // State
    let currentColor = '#7f13ec'; // Default

    // --- Init ---
    updateColor(currentColor);

    // --- Event Listeners ---

    colorInput.addEventListener('input', (e) => {
        updateColor(e.target.value);
    });

    pipetteBtn.addEventListener('click', () => {
        // Trigger the native color picker via the hidden input
        colorInput.click();
    });

    // EyeDropper API Support (Modern Browsers only)
    if (window.EyeDropper) {
        pipetteBtn.onclick = async () => {
            try {
                const eyeDropper = new EyeDropper();
                const result = await eyeDropper.open();
                updateColor(result.sRGBHex);
                colorInput.value = result.sRGBHex;
            } catch (e) {
                // User canceled or not supported, fallback to input click
                colorInput.click();
            }
        };
    }

    copyMainBtn.addEventListener('click', () => {
        copyToClipboard(copyCodeInput.value);
    });

    // Exports
    exportTailwind.addEventListener('click', () => {
        const code = `primary: '${currentColor}', // Generated by Color Library`;
        copyToClipboard(code);
    });

    exportSass.addEventListener('click', () => {
        const rgb = hexToRgb(currentColor);
        const code = `$brand-primary: ${currentColor}; // rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`;
        copyToClipboard(code);
    });

    exportCss.addEventListener('click', () => {
        const code = `--brand-primary: ${currentColor};`;
        copyToClipboard(code);
    });

    // --- Global Functions (Exposed for Palettes) ---
    window.loadColor = function (hex) {
        colorInput.value = hex;
        updateColor(hex);
        // Scroll top smoothly
        window.scrollTo({ top: 0, behavior: 'smooth' });
    };

    // --- Core Logic ---

    function updateColor(hex) {
        currentColor = hex;

        // Update Displays
        previewBox.style.backgroundColor = hex;
        previewBox.style.boxShadow = `0 0 15px ${hex}80`; // 50% opacity glow
        hexDisplay.textContent = hex.toUpperCase();

        const rgb = hexToRgb(hex);
        rgbDisplay.textContent = `${rgb.r}, ${rgb.g}, ${rgb.b}`;

        const hsl = rgbToHsl(rgb.r, rgb.g, rgb.b);
        hslDisplay.textContent = `${hsl.h}°, ${hsl.s}%, ${hsl.l}%`;

        const cmyk = rgbToCmyk(rgb.r, rgb.g, rgb.b);
        cmykDisplay.textContent = `${cmyk.c}, ${cmyk.m}, ${cmyk.y}, ${cmyk.k}`;

        // Update Default Export Text
        copyCodeInput.value = `export default { primary: '${hex.toUpperCase()}' }`;
    }

    function copyToClipboard(text) {
        navigator.clipboard.writeText(text).then(() => {
            // Animate Feedback
            copyFeedbackBar.style.width = '100%';
            setTimeout(() => {
                copyFeedbackBar.style.width = '0';
            }, 1000);

            // Temporary button feedback
            const originalIcon = copyMainBtn.innerHTML;
            // Only if triggered by main button
            if (arguments.callee.caller === copyMainBtn.onclick) {
                // ... logic if needed
            }
        });
    }

    // --- Converters ---

    function hexToRgb(hex) {
        // Expand shorthand form (e.g. "03F") to full form (e.g. "0033FF")
        var shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
        hex = hex.replace(shorthandRegex, function (m, r, g, b) {
            return r + r + g + g + b + b;
        });

        var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        return result ? {
            r: parseInt(result[1], 16),
            g: parseInt(result[2], 16),
            b: parseInt(result[3], 16)
        } : { r: 0, g: 0, b: 0 };
    }

    function rgbToHsl(r, g, b) {
        r /= 255, g /= 255, b /= 255;
        var max = Math.max(r, g, b), min = Math.min(r, g, b);
        var h, s, l = (max + min) / 2;

        if (max == min) {
            h = s = 0; // achromatic
        } else {
            var d = max - min;
            s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
            switch (max) {
                case r: h = (g - b) / d + (g < b ? 6 : 0); break;
                case g: h = (b - r) / d + 2; break;
                case b: h = (r - g) / d + 4; break;
            }
            h /= 6;
        }

        return {
            h: Math.round(h * 360),
            s: Math.round(s * 100),
            l: Math.round(l * 100)
        };
    }

    function rgbToCmyk(r, g, b) {
        var c = 1 - (r / 255);
        var m = 1 - (g / 255);
        var y = 1 - (b / 255);
        var k = Math.min(c, Math.min(m, y));

        c = (c - k) / (1 - k);
        m = (m - k) / (1 - k);
        y = (y - k) / (1 - k);

        if (isNaN(c)) c = 0;
        if (isNaN(m)) m = 0;
        if (isNaN(y)) y = 0;
        if (isNaN(k)) k = 1;

        return {
            c: Math.round(c * 100),
            m: Math.round(m * 100),
            y: Math.round(y * 100),
            k: Math.round(k * 100)
        };
    }
});
